### ISSUE TITLE
깃허브 코딩 에이전트 사용을 위한 저장소 기본 환경구축 및 워크플로/패키지 사전세팅

### ISSUE THREAD

**Issue by tjqjaqhd** [tjqjaqhd/dev#1]
GitHub 코딩 에이전트(GitHub Coding Agent)를 활용한 풀스택 개발 환경을 구축하기 위해 아래 항목들을 사전에 준비해야 합니다.

## 1. 저장소 기본 구조 및 환경 설정
- 프로젝트 구조 설계 (예: backend, frontend, docs, .github 등)
- 필수 디렉터리 및 파일 생성 (.gitignore, README.md 등)
- 기본 워크플로우(CI/CD, lint, test 등) 설정
- 권한/액세스 및 환경 변수 관리

## 2. Copilot Coding Agent 워크플로 및 패키지 사전 세팅
- `.github/workflows/copilot-setup-steps.yml` 파일 작성 및 추가
  - 예시:
    ```yaml
    name: Copilot Setup Steps
    on:
      workflow_dispatch:
    jobs:
      copilot-setup-steps:
        runs-on: ubuntu-latest
        steps:
          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '20'
          - name: Install backend dependencies
            run: cd backend && npm ci
          - name: Install frontend dependencies
            run: cd frontend && npm ci
          - name: Install additional tools
            run: sudo apt-get install -y jq
    ```
- 프로젝트에 필요한 종속성(패키지) 및 툴을 패키지 매니저(npm, pip, apt 등)로 미리 설치
- 워크플로에서 반드시 필요한 환경 변수, 시크릿, 설정파일 등 사전 구성

## 3. 추가 참고 및 개선 요청
- 코딩 에이전트의 원활한 자동화 작업을 위해 위 내용을 반드시 반영
- 추가로 필요한 패키지나 세부 설정, 가이드 문서 등이 있다면 코멘트로 남겨주세요.

---
참고: [Copilot Coding Agent 환경설정 공식 가이드](https://docs.github.com/en/copilot/customizing-copilot/customizing-the-development-environment-for-copilot-coding-agent)
